### ISSUE TITLE
xmlPath getting attribute which doesn't exist returns "[]"

### ISSUE THREAD

**Issue by rzeh4n** [jayway/rest-assured#650] opened 2016-02-20 20:37 UTC
```XmlPath.getString("item[3].@type")``` returns ```"[]"``` instead of ```""``` or ```null``` when attribute type is not present in item (specified by order). It seem inconsistent with results for items that have attribute with either empty or nonempty value (result is the value, possibly empty string, not in []).
Version: 2.8.0
Here is test demonstrating this:
```
// Given
String xml = "  <root>" //
            + "   <item type=\"normal\">item_1_content</item>"//
            + "   <item type=\"special\">item_1_content</item>"//
            + "   <item type=\"\">item_1_content</item>"//
            + "   <item>item_2_content</item>"//
            + " </root>";

// When
XmlPath xmlPath = new XmlPath(xml).setRoot("root");

// Then
assertThat(xmlPath.getString("item[0].@type"), equalTo("normal"));
assertThat(xmlPath.getString("item[1].@type"), equalTo("special"));
assertThat(xmlPath.getString("item[2].@type"), equalTo(""));
assertThat(xmlPath.getString("item[3].@type"), equalTo(""));// isEmptyOrNullString() fails as well
// the fact, that values are separated by ", " instead of "," is little suprising,
// but I suppose it's meant for human-readable output
assertThat(xmlPath.getString("item.@type"), equalTo("[normal, special, ]"));
```

**Comment by johanhaleby** [comment] 2016-02-21 15:36
`assertThat(xmlPath.getString("item[3].@type")` is problematic (see issue [here](https://github.com/jayway/rest-assured/issues/637)), the others are fine. When you do `item.@type` it'll return a list of all types but you force the result to be a string (which it's not) so thus REST Assured will do a toString on the list. I'll close the issue since it's a duplicate of issue 637

**Comment by johanhaleby** [comment] 2016-02-21 15:45
Sorry this is not the same issue as 637, I was mistaken.

**Comment by johanhaleby** [comment] 2016-02-21 15:49
I've now fixed this in master. thanks for reporting

**Closed by johanhaleby** 2016-02-21 15:49 UTC
