### ISSUE TITLE
JSON key with "-" in does not behave as expected if the value is an array

### ISSUE THREAD

**Issue by matsev** [jayway/rest-assured#618] opened 2015-11-20 11:05 UTC
Using json path with keys that contains `-` character does not work as expected when dealing with arrays.

### Preconditions
Given the following response body:
```json
{
    "alpha-beta": [
        0,
        1
    ]
}
```

And the following assertion:

```java
when()
    .get("/some-resource")
.then()
    .statusCode(OK.value())
    .body("alpha-beta[0]", is(0))
    .body("alpha-beta[1]", is(1))
```

### Expected result:

- The test should pass.

### Actual result:

- The test fails: `java.lang.IllegalArgumentException: The parameter "beta" was used but not defined. Define parameters using the JsonPath.params(...) function``

## Workaround 

Quote and escape the key used in the json path, e.g. `\"alpha-beta\"`

```java
when()
    .get("/some-resource")
.then()
    .statusCode(OK.value())
    .body("\"alpha-beta\"[0]", is(0))
    .body("\"alpha-beta\"[1]", is(1))
```

### Dependency
testCompile('com.jayway.restassured:rest-assured:2.7.0')

**Comment by johanhaleby** [comment] 2015-11-20 12:38
Duplicate of <a href="https://github.com/jayway/rest-assured/issues/564">issue 564</a> (please read last my comment on that issue and tell me what you think).

**Closed by johanhaleby** 2015-11-20 12:38 UTC
