### ISSUE TITLE
Special Character String encoding using UTF-8 not happening for json content type

### ISSUE THREAD

**Issue by cgowda** [jayway/rest-assured#613] opened 2015-11-05 12:16 UTC
I have a string 'äöüß€’ ' (German) which is one of the attribute in json object. when I hit the url  using RestAssured API, above mentioned string is encoded as "Ã¤Ã¶Ã¼ÃŸâ‚¬â€™" . I assume this is 'ISO-8859-1' encoding but i would want UTF-8 encoding. I tried using ObjectMapperType but i still have the same 'ISO-8859-1' encoding issue instead of UTF-8 encoding.

RestAssured.given().request().contentType(ContentType.JSON).log().all().body(object1,ObjectMapperType.JACKSON_2).post(URL);

**Comment by johanhaleby** [comment] 2015-11-05 12:42
Thanks for reporting.

What if you configure default charset to be UTF-8?

```java
given().
		config(RestAssured.config().config(DecoderConfig.config().defaultContentCharset("UTF-8"))).
		contentType(ContentType.JSON).
		log().all().
		body(object1,ObjectMapperType.JACKSON_2).
when().
		post(URL).
then(). ...
```

**Comment by cgowda** [comment] 2015-11-06 04:24
I tried with all (encoderConfig, decoderConfig and ObjectMapperConfig) but it's not working.

.setConfig(RestAssuredConfig.config().encoderConfig(EncoderConfig.encoderConfig().defaultContentCharset("UTF-8")))

**Comment by johanhaleby** [comment] 2016-01-08 10:33
I can't reproduce it, see my test [here](https://github.com/jayway/rest-assured/blob/master/examples/rest-assured-itest-java/src/test/java/com/jayway/restassured/itest/java/UnicodeITest.java#L64).

**Comment by cgowda** [comment] 2016-01-13 09:14
Thanks for the response.
Iam using Virgo nano server with spring framework.  When I try to hit the server using POSTMAN client it works fine.  I pass the JSON object containing following attrbutes.

{"name": "äöüß€’", "uri": "D:\\ProjectData", "description": "Desc"}

At the receiving end, REST controller will receive exactly same data. 
But if try the same with RESTAssured framework, the RESTController does 
receive name as  ' Ã¤Ã¶Ã¼ÃŸâ‚¬â€™ ' which is 'ISO-8859-1' encoding.

    RestAssured.given().contentType(ContentType.JSON). body(project).
                                                     when().post( PROJECTURL). then().
                                                         statusCode(200).body("name", Matchers.equalTo("äöüß€’"));

The only difference  is you are using JETTY server and Iam using VIRGO NANO.  Iam not sure what could be the issue here ?

**Comment by johanhaleby** [comment] 2016-01-13 09:24
What version of REST Assured are you using?

**Comment by cgowda** [comment] 2016-01-13 09:29
REST ASSURED-2.7.0. 
     One more point, I just put the log in RESTASSURED , following is printed.

Request method:	POST
Request path:	http://localhost:80/myproject/project
Proxy:			<none>
Request params:	<none>
Query params:	<none>
Form params:	<none>
Path params:	<none>
Multiparts:		<none>
Headers:		Accept=*/*
				Content-Type=application/json; charset=UTF-8
Cookies:		<none>
Body:
{
    "uri": "C:\\",
    "name": "Ã¤Ã¶Ã¼ÃŸâ‚¬â€™",
    "description": "XIL project"
}

So i think RESTASSURED is enconding the data using 'ISO-8859-1' .

**Comment by johanhaleby** [comment] 2016-01-13 09:42
What JSON serializer are you using (i.e. which one(s) do you have in classpath)?

**Comment by johanhaleby** [comment] 2016-01-13 09:43
Also try upgrading to 2.8.0

**Comment by cgowda** [comment] 2016-01-13 09:52
com.fasterxml.jackson.core.jackson-annotations-2.4.0.jar,
com.fasterxml.jackson.core.jackson-core-2.4.0.jar,
com.fasterxml.jackson.core.jackson-databind-2.4.0.jar

These are the jars iam using for serializing and deserializing.  
Sure, i will check with 2.8.0

**Comment by cgowda** [comment] 2016-01-13 10:21
Sorry, same issue is occuring with 2.8.0. 

Request method:	POST
Request path:	http://localhost:80/myproject/project
Proxy:			<none>
Request params:	<none>
Query params:	<none>
Form params:	<none>
Path params:	<none>
Multiparts:		<none>
Headers:		Accept=*/*
				Content-Type=application/json; charset=UTF-8
Cookies:		<none>
Body:
{
    "uri": "C:\\",
    "name": "Ã¤Ã¶Ã¼ÃŸâ‚¬â€™",
    "description": "XIL project"
}

**Comment by johanhaleby** [comment] 2016-01-22 07:09
Have you managed to find a workaround for this or is it still a problem?

**Comment by cgowda** [comment] 2016-01-25 04:08
Not yet..It is still an issue.

**Comment by Mehdzor** [comment] 2016-03-01 08:26
Same here for cyrillic symbols

**Comment by pumano** [comment] 2016-03-09 11:57
Looks like you guys use not a latest version of Rest Assured, it 100% works in 2.9.0 with cyrillic symbols and hope for others too.
Its has been fixed in 2.5.0:
Note from Change log 2.5.0 (2015-08-09):
"Pretty-printing of JSON now displays unicode characters correctly (issue 556)"

Just add new library and it will works. My logging now show utf-8 correctly in output.

**Comment by johanhaleby** [comment] 2016-04-29 09:46
There has also been some updates on this in version 2.9.1-SNAPSHOT so improvements will be included in the next release as well.

**Closed by johanhaleby** 2016-04-29 09:46 UTC

**Comment by Diptman** [comment] 2017-12-22 07:31
@johanhaleby I'm using Rest Assured version 3.0.6 Facing similar issue for one response only. Response consists of quotes " '  "  , error logs are as below: 

`at io.restassured.internal.ResponseSpecificationImpl.content(ResponseSpecificationImpl.groovy:265)
	at io.restassured.specification.ResponseSpecification$content$0.callCurrent(Unknown Source)
	at io.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:248)
	at io.restassured.internal.ValidatableResponseOptionsImpl.body(ValidatableResponseOptionsImpl.java:268)` 

Expected :  'ResponseWithSpecialChar' 
Actuals :  â€˜ResponseWithSpecialCharâ€™ 

Can you please help me with this?

**Comment by johanhaleby** [comment] 2017-12-22 11:26
What content is returned? What charset does the server specify?

**Comment by Diptman** [comment] 2017-12-26 02:48
Content-Type=application/xml  , charset = UTF-8

**Comment by Diptman** [comment] 2018-01-02 14:45
@johanhaleby  Issue is resolved. Issue was with my .java files. I just opened my code on linux machine and there were few special characters added to my files (diamond with a question mark), those I was not able to see on windows machine or on Notepad++. I still don't know why it happened. But my code is now working :)
