### ISSUE TITLE
RequestSpecification parameters(Map<String, ?> parametersMap) does not work with Collection Keys

### ISSUE THREAD

**Issue by falkorichter** [jayway/rest-assured#619] opened 2015-11-25 17:52 UTC
This groovy code should set a collection of Strings as the parameter with key objects
```
def objects = ["string1", "string2"]
expect().statusCode(200).body(equalTo("true"))
                .given()
                .when()
                .param("objects", objects)
                .get(TestSetup.getServerBaseUri() + "path")

expect().statusCode(200).body(equalTo("true"))
                .given()
                .when()
                .parameters([objects : objects])
                .get(TestSetup.getServerBaseUri() + "path")
```
The problem with the ```RequestSpecification parameters(Map<String, ?> parametersMap);```method, it does not treat a Collection key in the map as a Collection. The collection is flattened as a String in the case of a GET request, instead of being sent as an array of objects as it is done in the ```RequestSpecification param(String parameterName, Collection<?> parameterValues);```method.

**Comment by johanhaleby** [comment] 2015-11-26 18:10
I think this is a duplicate of [issue 238](https://github.com/jayway/rest-assured/issues/238).

**Closed by johanhaleby** 2015-11-26 18:10 UTC
