### ISSUE TITLE
Request content type is set to #toString of response content type object

### ISSUE THREAD

**Issue by ThorbenLindhauer** [jayway/rest-assured#616] opened 2015-11-13 14:04 UTC
Request that reproduces the issue:

```java
String url = ...;

given()
    .then().expect().statusCode(Status.OK.getStatusCode())
    .and()
      .contentType(equalTo(ContentType.TEXT))
    .when().get(url);
```

Note that the response content type is specified with a Hamcrest matcher. When the request is issued, the request content type header is set to `equalTo(ContentType.TEXT).toString()`. This may not be a valid media type, so the request may fail.

After doing some debugging, this seems to be the code that causes the problem: https://github.com/jayway/rest-assured/blob/master/rest-assured/src/main/java/com/jayway/restassured/internal/http/HTTPBuilder.java#L928-L931

**Comment by johanhaleby** [comment] 2015-11-13 15:23
Thanks for reporting

**Comment by johanhaleby** [comment] 2015-12-18 06:21
I'm trying to look into this now but I don't quite get it. Where do you find that  `equalTo(ContentType.TEXT).toString()` is used as a request content type!? Do you mean just `ContentType.TEXT.toString()`?  But `ContentType.TEXT.toString()` will always return `text/plain` which indeed is a valid media type.

**Comment by ThorbenLindhauer** [comment] 2015-12-18 07:04
Hi @johanhaleby 

Thanks for looking into this issue.

If I remember correctly, the problem was that the code 

```
given()
    .then().expect().statusCode(Status.OK.getStatusCode())
    .and()
      .contentType(equalTo(ContentType.TEXT))
    .when().get(url);
```

sets `equalTo(ContentType.TEXT)` as the content type, which is a Hamcrest matcher and [in line 932 of HttpBuilder](https://github.com/jayway/rest-assured/blob/master/rest-assured/src/main/java/com/jayway/restassured/internal/http/HTTPBuilder.java#L932) the request content type is set to `Matcher#toString` if no request content type is set, which results in `"text/plain"` (note the quotes).

Cheers,
Thorben

**Comment by johanhaleby** [comment] 2015-12-18 07:59
Oh now I see what's going on. Please note the type signature of `Matcher<? super String>`:

![image](https://cloud.githubusercontent.com/assets/187029/11891982/152a1ed4-a564-11e5-9a79-51e9613f44f9.png)

You shouldn't pass a `ContentType` to a Hamcrest matcher for validation. Unfortunately Java's type system is too weak to catch the error at compile time and let it slip through. This means that the content-type returned in the response is a String but Hamcrest will try to match it against a `ContentType` and thus fail. What you should do is:

```java
when().
        get("/text").
then().
        statusCode(200).
        contentType(ContentType.TEXT);
```

I.e. don't use a Hamcrest matcher.

I'll close the issue since this is expected behavior and I don't think there's anything we can do about it. If you disagree then feel free to reopen :)

**Closed by johanhaleby** 2015-12-18 07:59 UTC

**Comment by ThorbenLindhauer** [comment] 2015-12-18 08:22
Just for clarification: Is there any use for Hamcrest matchers then? 

When I write

```
given()
    ...
    .then().expect()
      ....
        .contentType(CoreMatchers.<String>either(equalTo(ContentType.TEXT.toString() + ";charset=UTF-8")).or(equalTo(ContentType.TEXT.toString() + " ;charset=UTF-8")))
        // match either "text/plain;charset=UTF-8" or "text/plain; charset=UTF-8"
      .when()
        .get(..);
```

Then then request content type header becomes `("text/plain;charset=UTF-8" or "text/plain ;charset=UTF-8")`.

**Comment by johanhaleby** [comment] 2015-12-18 09:29
The reason Hamcrest is there is for advanced cases not covered by `ContentType` matching. For example if you care about the charset (which is ignored in `ContentType` matching if I remember it correctly).
